spring:
  rabbitmq:
    host: rabbitmq.adds
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.146.210:3306/tb71
    username: taobao71
    password: taobao71
    type: com.alibaba.druid.pool.DruidDataSource
